//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heritage_ActiveStudents
    {
        public int UserId { get; set; }
        public Nullable<int> ClassTeacherId { get; set; }
        public int InstanceId { get; set; }
        public int RoleId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> ChangePwOnLogin { get; set; }
        public Nullable<int> SecurityQuestionId { get; set; }
        public string Answer { get; set; }
        public string InstanceUserCode { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string PortalEmail { get; set; }
        public string AlternateEmail { get; set; }
        public string WebAddress { get; set; }
        public string Hobbies { get; set; }
        public string Photo { get; set; }
        public Nullable<double> PhotoSize { get; set; }
        public string MobilePhone { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string WorkPhoneExtension { get; set; }
        public string FaxNumber { get; set; }
        public string MailingAddress1 { get; set; }
        public string MailingAddress2 { get; set; }
        public string PermanentAddress1 { get; set; }
        public string PermanentAddress2 { get; set; }
        public string EmergencyContactNumber1 { get; set; }
        public string EmergencyContactNumber2 { get; set; }
        public string AdmissionNumber { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public Nullable<int> CasteId { get; set; }
        public string CollegeCode { get; set; }
        public Nullable<int> StudentQuota { get; set; }
        public Nullable<int> BloodGroup { get; set; }
        public Nullable<int> RouteId { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> PCountryId { get; set; }
        public Nullable<int> PStateId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string POtherState { get; set; }
        public string OtherState { get; set; }
        public string PCity { get; set; }
        public string City { get; set; }
        public string PZip { get; set; }
        public string Zip { get; set; }
        public int InstanceClassificationId { get; set; }
        public Nullable<int> InstanceSubClassificationId { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public string FolderMemorySize { get; set; }
        public string InboxMemorySize { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Batch { get; set; }
        public Nullable<int> Transport { get; set; }
        public Nullable<int> StopId { get; set; }
        public Nullable<int> MotherTongueId { get; set; }
        public string knownLanguages { get; set; }
        public Nullable<int> InstanceHouseId { get; set; }
        public Nullable<int> InstanceBlockId { get; set; }
        public string Qualification { get; set; }
        public Nullable<bool> TCTaken { get; set; }
        public Nullable<bool> SendSMS { get; set; }
        public Nullable<int> StudentStatus { get; set; }
        public Nullable<bool> CollegeHostel { get; set; }
        public Nullable<int> DietaryNeeds { get; set; }
        public string DietaryNeedsDetails { get; set; }
        public Nullable<int> DisabilityId { get; set; }
        public string DisabilityDetails { get; set; }
        public string PlaceOfBirth { get; set; }
        public string StudentIdentificationMarks { get; set; }
        public Nullable<bool> SiblingsInSameCollege { get; set; }
        public string SiblingsInSameCollegeDetails { get; set; }
        public string PersonalDoctorDetails { get; set; }
        public string InstanceTransferDetails { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> LabBatchId { get; set; }
        public string HallTicket { get; set; }
        public Nullable<int> CommunityId { get; set; }
        public string TCNumber { get; set; }
        public Nullable<System.DateTime> TCDate { get; set; }
        public string TCComments { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public string SpousePhno { get; set; }
        public string SpouseName { get; set; }
        public string Weight { get; set; }
        public string Height { get; set; }
        public string Ailments { get; set; }
        public string ReferenceBy { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<bool> IS_UserJoined { get; set; }
        public Nullable<bool> SibilingInOtherCollege { get; set; }
        public Nullable<int> DropRouteId { get; set; }
        public Nullable<int> DropStopId { get; set; }
    }
}
