//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaxfortIndividualpaymentDetail
    {
        public Nullable<int> Userid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<System.DateTime> datedate { get; set; }
        public int tablepri { get; set; }
    }
}
