//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maxfort_matched25_june
    {
        public Nullable<long> UserID { get; set; }
        public string STUDENT_FIRST_NAME { get; set; }
        public string STUDENT_LAST__NAME { get; set; }
        public string MODE { get; set; }
        public Nullable<double> APRIL__Amount_Paid_ { get; set; }
        public string APRIL__Amount_Paid_Date_ { get; set; }
        public string ModifiedDate { get; set; }
        public string CLASS { get; set; }
        public Nullable<double> ANNUALFEE { get; set; }
        public Nullable<double> DEVFEE { get; set; }
        public Nullable<double> TUITIONFEE { get; set; }
        public Nullable<double> ACTIVITYFEE { get; set; }
        public string NEWSPAPER { get; set; }
        public Nullable<double> TPT { get; set; }
        public Nullable<double> Fine_Amount { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<double> BALANCE { get; set; }
        public string MonthName { get; set; }
        public string F19 { get; set; }
        public Nullable<double> Maountcalculation { get; set; }
        public bool status { get; set; }
        public Nullable<int> Monthstatus { get; set; }
    }
}
