//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class sampleUser
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> Age { get; set; }
        public string Location { get; set; }
        public string Occupation { get; set; }
        public string Interests { get; set; }
        public Nullable<bool> Gender { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
