//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class STEPS_STUDATA
    {
        public string STUDENTUID { get; set; }
        public Nullable<decimal> AADHAARID { get; set; }
        public string STUDENTNAME { get; set; }
        public string Student_MiddleName { get; set; }
        public string Student_LastName { get; set; }
        public string FATHERNAME { get; set; }
        public string MOTHERNAME { get; set; }
        public string HABCD { get; set; }
        public System.DateTime DOB { get; set; }
        public decimal GENDERID { get; set; }
        public Nullable<decimal> SOCIALCATID { get; set; }
        public Nullable<decimal> RELIGIONID { get; set; }
        public Nullable<decimal> MOTONGUEID { get; set; }
        public string AC_YEAR { get; set; }
        public string STATECD { get; set; }
        public string DISTCD { get; set; }
        public string BLKCD { get; set; }
        public string CLUCD { get; set; }
        public string VILCD { get; set; }
        public string SCHCD { get; set; }
        public System.DateTime DOA { get; set; }
        public string ADMNNO { get; set; }
        public Nullable<decimal> BPL_YN { get; set; }
        public Nullable<decimal> DISADV_YN { get; set; }
        public Nullable<decimal> FREEEDU_YN { get; set; }
        public decimal CURCLASS { get; set; }
        public decimal PRVCLASS { get; set; }
        public Nullable<decimal> PRVCLASS_STATUS { get; set; }
        public Nullable<decimal> ATTENDANCE { get; set; }
        public decimal MEDINSTR { get; set; }
        public Nullable<decimal> DISABILITYID { get; set; }
        public Nullable<decimal> CWSNFACILITY1 { get; set; }
        public Nullable<decimal> CWSNFACILITY2 { get; set; }
        public Nullable<decimal> CWSNFACILITY3 { get; set; }
        public Nullable<decimal> CWSNFACILITY4 { get; set; }
        public Nullable<decimal> FREETEXTBK_YN { get; set; }
        public Nullable<decimal> FREEUNIFORM_YN { get; set; }
        public Nullable<decimal> FREETRANSPORT_YN { get; set; }
        public Nullable<decimal> FREEESCORT_YN { get; set; }
        public Nullable<decimal> FREEHOSTEL_YN { get; set; }
        public Nullable<decimal> SPECIALTRNG_YN { get; set; }
        public Nullable<decimal> HOMELESS_YN { get; set; }
        public Nullable<decimal> EXAMMARKS { get; set; }
        public Nullable<decimal> STREAM { get; set; }
        public Nullable<decimal> SECTOR { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> MOBILE { get; set; }
        public decimal CHECKBIT { get; set; }
        public Nullable<decimal> CLSEC { get; set; }
        public Nullable<decimal> MDM_YN { get; set; }
        public Nullable<decimal> IRONTAB_YN { get; set; }
        public Nullable<decimal> DEWORMTAB_YN { get; set; }
        public Nullable<decimal> VITATAB_YN { get; set; }
        public Nullable<decimal> XMAPPR_YN { get; set; }
        public Nullable<decimal> XMPASS_YN { get; set; }
        public string ACCOUNTNO { get; set; }
        public string IFSC { get; set; }
        public bool Student_Insert_Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
