//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAptechLoginBrowserDetail
    {
        public int AptechLoginID { get; set; }
        public string IPAdress { get; set; }
        public string URL { get; set; }
        public Nullable<int> CandidateLogin { get; set; }
        public Nullable<System.DateTime> CandidateLoginDate { get; set; }
        public string BrowserVersion { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
