//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccidentHistory
    {
        public int AccidentHistoryId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> BusID { get; set; }
        public int Type { get; set; }
        public System.DateTime AccidentDate { get; set; }
        public string AccidentLocation { get; set; }
        public Nullable<bool> PoliceCaseFiled { get; set; }
        public string CaseDetails { get; set; }
        public string InjuryDetails { get; set; }
        public Nullable<decimal> LossIncurred { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Deleteflag { get; set; }
    }
}
