//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttendanceExtension
    {
        public int AttendanceExtPKId { get; set; }
        public Nullable<int> AttendanceID { get; set; }
        public Nullable<int> AttendanceLogIdBio { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public string ShiftSName { get; set; }
        public string InTimeHrs { get; set; }
        public string InTimeMins { get; set; }
        public string OutTimeHrs { get; set; }
        public string OutTimeMins { get; set; }
        public string DurationHrs { get; set; }
        public string DurationMins { get; set; }
        public string OverTimeHrs { get; set; }
        public string OverTimeMins { get; set; }
        public string TotalDurHrs { get; set; }
        public string TotalDurMins { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public string InDeviceId { get; set; }
        public string OutDeviceId { get; set; }
        public string LateBy { get; set; }
        public string EarlyBy { get; set; }
        public Nullable<int> IsOnLeave { get; set; }
        public string LeaveType { get; set; }
        public Nullable<double> LeaveDuration { get; set; }
        public Nullable<int> WeeklyOff { get; set; }
        public Nullable<int> Holiday { get; set; }
        public string LeaveRemarks { get; set; }
        public string PunchRecords { get; set; }
        public Nullable<double> Present { get; set; }
        public Nullable<double> Absent { get; set; }
        public string StatusCode { get; set; }
        public string P1Status { get; set; }
        public string P2Status { get; set; }
        public string P3Status { get; set; }
        public Nullable<int> IsonSpecialOff { get; set; }
        public string SpecialOffType { get; set; }
        public string SpecialOffRemark { get; set; }
        public Nullable<int> SpecialOffDuration { get; set; }
        public Nullable<int> OverTimeE { get; set; }
        public Nullable<int> MissedOutPunch { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> MissedInPunch { get; set; }
        public string C1 { get; set; }
        public string C2 { get; set; }
        public string C3 { get; set; }
        public string C4 { get; set; }
        public string C5 { get; set; }
        public string C6 { get; set; }
        public string C7 { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public Nullable<int> OverTime { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<int> AttendanceType { get; set; }
        public string SplAttenanceComments { get; set; }
        public Nullable<int> LateByMins { get; set; }
        public Nullable<int> EarlyLeavingByMins { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<bool> IsLeaveRecord { get; set; }
    }
}
