//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmissionFee_ChequeTracking
    {
        public int AdmFeeChequeTrackingID { get; set; }
        public int EnquiryDetailsId { get; set; }
        public int InstanceId { get; set; }
        public string ChequeDDNo { get; set; }
        public Nullable<System.DateTime> ChequeDDDate { get; set; }
        public string ChequeDDBank { get; set; }
        public string ChequeDDBranch { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> ChequeTakenStatus { get; set; }
        public Nullable<int> ChequeStatus { get; set; }
        public Nullable<int> paymentstatus { get; set; }
        public Nullable<System.DateTime> ChequeDepositedDate { get; set; }
        public Nullable<System.DateTime> ChequeClearedDate { get; set; }
        public string RoutingNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string DepositedChequeDocument { get; set; }
        public string DepositedDocSize { get; set; }
        public string ChequeDocument { get; set; }
        public string DocSize { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    }
}
