//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuditField
    {
        public int AuditFieldId { get; set; }
        public int InstanceId { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> AuditTypeId { get; set; }
        public Nullable<int> AlertUserId { get; set; }
        public string AlertFieldValue { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    
        public virtual tblAuditType tblAuditType { get; set; }
    }
}
