//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssetItemDetail
    {
        public int ItemDetailsId { get; set; }
        public int InstanceId { get; set; }
        public int AssetDetailsId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemDescription { get; set; }
        public string ItemIdNumber { get; set; }
        public string ItemBrandName { get; set; }
        public string ItemModel { get; set; }
        public string ItemType { get; set; }
        public Nullable<System.DateTime> ItemDateOfPurchase { get; set; }
        public Nullable<int> ItemPurchaseTimeInHrs { get; set; }
        public Nullable<int> ItemPurchaseTimeInMins { get; set; }
        public Nullable<System.DateTime> ItemReplacementDate { get; set; }
        public Nullable<System.DateTime> ItemPreviousServiceDate { get; set; }
        public Nullable<System.DateTime> ItemNextServiceDate { get; set; }
        public string ItemVendorName { get; set; }
        public string ItemVendorAddress { get; set; }
        public string ItemVerdorMobileNumber { get; set; }
        public Nullable<System.DateTime> ItemWarrentyStartDate { get; set; }
        public Nullable<System.DateTime> ItemWarrentyEndDate { get; set; }
        public Nullable<int> ItemWarrenty { get; set; }
        public string ItemWarrentyStatus { get; set; }
        public string ItemLocation { get; set; }
        public Nullable<decimal> ItemValue { get; set; }
        public Nullable<System.DateTime> ItemManufacturedDate { get; set; }
        public string ItemRoomNo { get; set; }
        public string ItemFloor { get; set; }
        public Nullable<int> ItemAssignedTo { get; set; }
        public string ItemImageOfAsset { get; set; }
        public string ItemStatus { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
