//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttendanceMark
    {
        public int AttendanceMarksId { get; set; }
        public Nullable<int> InstanceId { get; set; }
        public Nullable<int> MinMarksPercentage { get; set; }
        public Nullable<int> MaxMarksPercentages { get; set; }
        public Nullable<int> AttendanceMarks { get; set; }
    }
}
