//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdvanceSearchData
    {
        public int UserId { get; set; }
        public string StudentFirstName { get; set; }
        public string ResumeTitle { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Gender { get; set; }
        public string MobilePhone { get; set; }
        public string PortalEmail { get; set; }
        public string SkillName { get; set; }
        public string PreferredLocation { get; set; }
        public string Qualification { get; set; }
        public string Specialization { get; set; }
        public string InstitutionName { get; set; }
        public Nullable<int> POYear { get; set; }
        public string UniversityName { get; set; }
        public string CompanyName { get; set; }
        public string Location { get; set; }
        public string Designation { get; set; }
        public string FunctionalArea { get; set; }
        public string Role { get; set; }
        public string IndustryType { get; set; }
        public string Salary { get; set; }
        public string CurrencyType { get; set; }
        public int PHits { get; set; }
        public string TotMonths { get; set; }
        public double SSCMarks { get; set; }
        public double IPEMarks { get; set; }
        public double DipMarks { get; set; }
        public double GradMarks { get; set; }
        public double PGMarks { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public int AdvanceSearchDataId { get; set; }
    }
}
