//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdhocSavedQuery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAdhocSavedQuery()
        {
            this.tblAdhocpostedqueries = new HashSet<tblAdhocpostedquery>();
        }
    
        public int QueryId { get; set; }
        public Nullable<int> InstanceID { get; set; }
        public string QueryName { get; set; }
        public string Query { get; set; }
        public string Description { get; set; }
        public string OrderBy { get; set; }
        public string GroupBy { get; set; }
        public string SelectedColumns { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAdhocpostedquery> tblAdhocpostedqueries { get; set; }
    }
}
