//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttendance
    {
        public int AttendanceID { get; set; }
        public int UserID { get; set; }
        public int SubjectSlotID { get; set; }
        public Nullable<bool> IsPresent { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public Nullable<int> MentorId { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpDatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public string PeriodName { get; set; }
    }
}
