//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssignStudentForExam
    {
        public int AssignStudentForExamId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> SSRUserId { get; set; }
        public Nullable<int> ManagerUserId { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<int> TestHRS { get; set; }
        public Nullable<int> TestMNS { get; set; }
        public Nullable<int> TestEndHRS { get; set; }
        public Nullable<int> TestEndMNS { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> AccessToOnline { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
