//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssignSubjectTool
    {
        public int InstanceSubjectToolId { get; set; }
        public Nullable<int> SubjectToolId { get; set; }
        public Nullable<int> ClassificationId { get; set; }
        public Nullable<int> SubClassificationId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> IncludeInRemarks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
