//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusRoute
    {
        public int BusRouteId { get; set; }
        public int BusId { get; set; }
        public int RouteId { get; set; }
        public System.DateTime EffectiveFromDate { get; set; }
        public System.DateTime EffectiveToDate { get; set; }
        public string MorningStartTime { get; set; }
        public string MorningEndTime { get; set; }
        public string EveningStartTime { get; set; }
        public string EveningEndTime { get; set; }
        public Nullable<int> BusTypeStatus { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
