//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBulkUpload
    {
        public int BulkUploadId { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public Nullable<int> Gender { get; set; }
        public string UserMobilePhone { get; set; }
        public string HomePhone { get; set; }
        public string RollNo { get; set; }
        public string AdmissionNo { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string UserPostalAddressLine1 { get; set; }
        public string UserPostalAddressLine2 { get; set; }
        public string City { get; set; }
        public Nullable<int> State { get; set; }
        public string Zip { get; set; }
        public string Studentpermanentaddressline1 { get; set; }
        public string Studentpermanentaddressline2 { get; set; }
        public string City1 { get; set; }
        public Nullable<int> State1 { get; set; }
        public string zip1 { get; set; }
        public string Emergency1ContactNumber1 { get; set; }
        public string Batch { get; set; }
        public Nullable<int> StudentQuota { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> Semester { get; set; }
        public string StudentIdentificationMarks { get; set; }
        public string ExtraCurricularActivityDetails { get; set; }
        public Nullable<int> MotherTongue { get; set; }
        public string KnownLanguages { get; set; }
        public string BloodGroup { get; set; }
        public string EmailId { get; set; }
        public string Hobbies { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> Religion { get; set; }
        public Nullable<int> Community { get; set; }
        public Nullable<int> Caste { get; set; }
        public string ParentFirstName { get; set; }
        public string ParentLastName { get; set; }
        public string ParentMobileNumber { get; set; }
        public string ParentOccupation { get; set; }
        public Nullable<int> Relationship { get; set; }
        public string ParentPostalAddressline1 { get; set; }
        public string ParentPostalAddressline2 { get; set; }
        public string city2 { get; set; }
        public Nullable<int> State2 { get; set; }
        public string Zip2 { get; set; }
        public string ParentPemanentAddressline1 { get; set; }
        public string ParentPemanentAddressline2 { get; set; }
        public string City3 { get; set; }
        public Nullable<int> State3 { get; set; }
        public string Zip3 { get; set; }
        public string ParentQualification { get; set; }
        public string ParentWorkPhoneNumber { get; set; }
        public Nullable<System.DateTime> DateofJoining { get; set; }
        public string StudentEmergencyContactNumber2 { get; set; }
        public Nullable<bool> Transport { get; set; }
        public Nullable<int> Route { get; set; }
        public Nullable<int> Stop { get; set; }
        public Nullable<bool> StayinginHostel { get; set; }
        public Nullable<bool> AnySiblingsinSchool { get; set; }
        public string SiblingDetails { get; set; }
        public Nullable<bool> PhysicallyChalenged { get; set; }
        public string PhysicallyChalengedDetails { get; set; }
        public string PersonalDoctorDetails { get; set; }
        public string FoodOffering1 { get; set; }
        public string FoodOffering2 { get; set; }
        public string FoodOffering3 { get; set; }
        public string FoodOffering4 { get; set; }
        public Nullable<int> DietaryNeed { get; set; }
        public string DietaryNeedDetails { get; set; }
        public Nullable<int> InstanceId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
