//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusServiceRepairDetail
    {
        public int BusServiceRepairId { get; set; }
        public int BusId { get; set; }
        public int StationId { get; set; }
        public int StationContactPersonId { get; set; }
        public bool IsRepair { get; set; }
        public System.DateTime PickUpDate { get; set; }
        public System.DateTime DropDate { get; set; }
        public Nullable<bool> IsFreeService { get; set; }
        public decimal Amount { get; set; }
        public decimal AtKms { get; set; }
        public decimal KmsAfterService { get; set; }
        public Nullable<System.DateTime> LastServiceDate { get; set; }
        public Nullable<System.DateTime> NextServiceDate { get; set; }
        public string Remarks { get; set; }
        public string ProblemsRectified { get; set; }
        public string Description { get; set; }
        public string DocumentName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Deleteflag { get; set; }
    }
}
