//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBioTempNIMRA2
    {
        public int TempPKId { get; set; }
        public Nullable<int> CheckinoutPK { get; set; }
        public Nullable<int> BioId { get; set; }
        public string BADGENUMBER { get; set; }
        public Nullable<System.DateTime> CHECKTIME { get; set; }
        public string CHECKTYPE { get; set; }
        public Nullable<int> VERIFYCODE { get; set; }
        public string SENSORID { get; set; }
        public string Memoinfo { get; set; }
        public Nullable<int> WorkCode { get; set; }
        public string sn { get; set; }
        public Nullable<short> UserExtFmt { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public int BioTempNIMRA2Id { get; set; }
    }
}
