//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusInfo
    {
        public int BusTypeId { get; set; }
        public int instanceId { get; set; }
        public string BusTypeName { get; set; }
        public string Make { get; set; }
        public string EngineModel { get; set; }
        public Nullable<System.DateTime> DateofMaking { get; set; }
        public string VehicleRegno { get; set; }
        public string ChasisNo { get; set; }
        public Nullable<int> BusCapacity { get; set; }
        public Nullable<int> FuelCapacity { get; set; }
        public Nullable<int> Milage { get; set; }
        public string ServicingLocation { get; set; }
        public Nullable<System.DateTime> LastServiceDate { get; set; }
        public Nullable<System.DateTime> NextServiceDate { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
        public string EngineNumber { get; set; }
        public Nullable<int> SpareCapacity { get; set; }
        public string ManufacturedBy { get; set; }
        public Nullable<System.DateTime> ManufacturedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
