//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBiometricJobOutput
    {
        public int ExecutionId { get; set; }
        public string Service { get; set; }
        public Nullable<int> NoOfRecords { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
