//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusDiary
    {
        public int BusDiaryId { get; set; }
        public int InstanceId { get; set; }
        public int DriverId { get; set; }
        public int BusId { get; set; }
        public decimal DailyTravel { get; set; }
        public decimal EndKmReading { get; set; }
        public Nullable<decimal> PrevKmsTravelled { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsExtraRun { get; set; }
        public Nullable<decimal> ExtraRunKms { get; set; }
        public string DocumentName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Deleteflag { get; set; }
        public Nullable<decimal> StartKmReading { get; set; }
        public Nullable<decimal> RouteLength { get; set; }
    }
}
