//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBookedResource
    {
        public int BookedResourceId { get; set; }
        public int InstanceId { get; set; }
        public Nullable<int> ResourceId { get; set; }
        public Nullable<int> BookedUserId { get; set; }
        public string SessionId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<int> UnitsBooked { get; set; }
        public string CollectingPerson { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    
        public virtual tblEResourceItem tblEResourceItem { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
