//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBulkUploadUsersAdmission
    {
        public int BulkUserUploadId { get; set; }
        public int InstanceId { get; set; }
        public string StudentId { get; set; }
        public string AadhaarNumber { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> AssessorId { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<int> LogisticsId { get; set; }
        public Nullable<int> JobRoleId { get; set; }
        public Nullable<System.DateTime> BatchStartDate { get; set; }
        public Nullable<System.DateTime> BatchEndDate { get; set; }
        public string CenterId { get; set; }
        public string BatchId { get; set; }
        public string Address { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public string ExamTimeHH { get; set; }
        public string ExamTimeMM { get; set; }
        public string ExamTimeHHEnd { get; set; }
        public string ExamTimeMMEnd { get; set; }
        public string CenterName { get; set; }
        public string EnrollmentNumber { get; set; }
        public string Fathers_HusbandName { get; set; }
        public string SheetName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Deleteflag { get; set; }
        public string IsDuplicate { get; set; }
        public string IdentificationType { get; set; }
        public string OtherID { get; set; }
        public Nullable<int> SchemeName { get; set; }
    }
}
