//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCommonData
    {
        public int ID { get; set; }
        public string CodeName { get; set; }
        public int value { get; set; }
        public string Data { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<int> Parentid { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
