//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClearanceType
    {
        public int ClearanceTypeID { get; set; }
        public int ModuleID { get; set; }
        public int InstanceID { get; set; }
        public int LevelID { get; set; }
        public string ClearanceName { get; set; }
        public Nullable<int> ParentClearanceTypeID { get; set; }
        public string ClearanceShortName { get; set; }
        public string ClearanceDisplayName { get; set; }
        public Nullable<byte> IsCommentsLevel { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
