//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompOffLeaf
    {
        public int CompOffLeaveID { get; set; }
        public int InstanceID { get; set; }
        public int AcademicYearID { get; set; }
        public int UserID { get; set; }
        public int LeaveTypeID { get; set; }
        public System.DateTime CompensationDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public Nullable<int> Day { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> deleteflag { get; set; }
    }
}
