//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChangeActivity
    {
        public int AuditTrailId { get; set; }
        public int InstanceId { get; set; }
        public int SourceId { get; set; }
        public string TableName { get; set; }
        public string AuditKey { get; set; }
        public string CurrentValue { get; set; }
        public string PreviousValue { get; set; }
        public int CurrentValueCreatedBy { get; set; }
        public System.DateTime CurrentValueCreatedDate { get; set; }
        public Nullable<int> PreviousValueCreatedBy { get; set; }
        public Nullable<System.DateTime> PreviousValueCreatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
