//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClassification
    {
        public int InstanceClassificationId { get; set; }
        public int InstanceId { get; set; }
        public string ClassificationName { get; set; }
        public string ClassificationDescription { get; set; }
        public Nullable<System.DateTime> AttendanceEffectiveDate { get; set; }
        public Nullable<System.DateTime> AttendanceEndDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
