//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCountryTimeZone
    {
        public int TimeZoneId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string TimeZoneName { get; set; }
        public string TimezoneDescription { get; set; }
        public Nullable<byte> DiffWithGMT { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Delete_Flag { get; set; }
    
        public virtual tblCountry tblCountry { get; set; }
    }
}
