//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDriver
    {
        public int DriverId { get; set; }
        public int instanceId { get; set; }
        public string SupervisorName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Photo { get; set; }
        public Nullable<double> PhotoSize { get; set; }
        public string MobilePhone { get; set; }
        public string HomePhone { get; set; }
        public string BloodGroup { get; set; }
        public string EmergencyContactNumber { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public Nullable<int> CasteId { get; set; }
        public string ResidingAddress { get; set; }
        public string RStreetName { get; set; }
        public string Rcity { get; set; }
        public Nullable<int> RstateId { get; set; }
        public string RotherState { get; set; }
        public Nullable<int> RCountryId { get; set; }
        public string Rzip { get; set; }
        public string WorkshopAddress1 { get; set; }
        public string WorkshopAddressLine2 { get; set; }
        public string WorkshopCity { get; set; }
        public Nullable<int> WorkshopStateId { get; set; }
        public string WorkshopOtherState { get; set; }
        public Nullable<int> WorkshopCountryId { get; set; }
        public string WorkshopZip { get; set; }
        public string WorkshopWorkPhone { get; set; }
        public string SupervisorMobileNo { get; set; }
        public Nullable<int> MotherTongueId { get; set; }
        public string KnownLanguages { get; set; }
        public string PersonalDoctorDetails { get; set; }
        public string LicenceNumber { get; set; }
        public string LicenceType { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> SendSMS { get; set; }
        public Nullable<bool> TransportFlag { get; set; }
        public string RefererName1 { get; set; }
        public string RefererDesignation1 { get; set; }
        public string RefererAddress1 { get; set; }
        public string RefererCity1 { get; set; }
        public Nullable<int> RefererCountryId1 { get; set; }
        public Nullable<int> RefererStateId1 { get; set; }
        public Nullable<int> RefererZipCode1 { get; set; }
        public string RefererPhoneNo1 { get; set; }
        public string RefererName2 { get; set; }
        public string RefererDesignation2 { get; set; }
        public string RefererAddress2 { get; set; }
        public string RefererCity2 { get; set; }
        public Nullable<int> RefererCountryId2 { get; set; }
        public Nullable<int> RefererStateId2 { get; set; }
        public Nullable<int> RefererZipCode2 { get; set; }
        public string RefererPhoneNo2 { get; set; }
        public string EmployerofCompany { get; set; }
        public string EmployerOfAddress { get; set; }
        public string ETelephoneNo { get; set; }
        public string EPositionHeld { get; set; }
        public string EsupervisorName { get; set; }
        public string ReasonsforLeaving { get; set; }
        public string OverallExp { get; set; }
        public string HealthCheckUp { get; set; }
        public Nullable<bool> DrugTest { get; set; }
        public string DrugTestReason { get; set; }
        public Nullable<bool> HearingAid { get; set; }
        public string HearingAidReason { get; set; }
        public Nullable<bool> VisionAid { get; set; }
        public string VisionAidReason { get; set; }
        public Nullable<bool> TrafficViolation { get; set; }
        public string TrafficViolationReason { get; set; }
        public Nullable<bool> PayRoll { get; set; }
        public string PayRollReason { get; set; }
        public Nullable<bool> EnforcementHistory { get; set; }
        public string EnforcementHistoryReason { get; set; }
        public Nullable<bool> LicenceRevoked { get; set; }
        public string LicenceRevokedReason { get; set; }
        public string SecondaryIns { get; set; }
        public string SecondaryPassedOut { get; set; }
        public string SecondaryClass { get; set; }
        public string OtherEduIns { get; set; }
        public string OtherPassedOut { get; set; }
        public string OtherClass { get; set; }
        public string DrivingIns { get; set; }
        public string DrivingCerti { get; set; }
        public string CertificationNo { get; set; }
        public Nullable<int> BusTypeId { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
        public Nullable<int> EmpTypeId { get; set; }
        public string EmergencyContactAddress { get; set; }
        public Nullable<int> IssuedBy { get; set; }
        public string IssuedByOther { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string ESINo { get; set; }
        public string Insurance { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public string BadgeNo { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string PermanentAddress { get; set; }
        public string WorkPhone { get; set; }
    }
}
