//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDayWiseShiftAllocation
    {
        public int DayWiseShiftallocationID { get; set; }
        public Nullable<int> ShiftAllocationID { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.TimeSpan> LateComingMins { get; set; }
        public Nullable<System.TimeSpan> EarlyGoingMins { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string DayWiseShiftallocation { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpDatedBy { get; set; }
        public Nullable<System.DateTime> UpdateedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
