//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExternalUserEduDetails_Heritage
    {
        public int EduDetailsId { get; set; }
        public int InstanceId { get; set; }
        public int UserId { get; set; }
        public string EduDetail { get; set; }
        public string YearofPassing { get; set; }
        public string University { get; set; }
        public string InstituteNameandLocation { get; set; }
        public string Subjects { get; set; }
        public Nullable<decimal> AggregateGrade { get; set; }
        public string SubjectSpecialization { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
