//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEResourceItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEResourceItem()
        {
            this.tblBookedResources = new HashSet<tblBookedResource>();
            this.tblEResourceAuthorizations = new HashSet<tblEResourceAuthorization>();
        }
    
        public int EResourceId { get; set; }
        public int InstanceId { get; set; }
        public int MainCategoryId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public string EResourceName { get; set; }
        public string Code { get; set; }
        public string ISBNNumber { get; set; }
        public string BookNumber { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<int> PublisherId { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string Comments { get; set; }
        public Nullable<int> TotalUnits { get; set; }
        public Nullable<int> AvailableUnits { get; set; }
        public string Capacity { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Room { get; set; }
        public string Shelf { get; set; }
        public string Location { get; set; }
        public Nullable<int> NoShowTime { get; set; }
        public Nullable<int> UnitLimit { get; set; }
        public string BookingLimit { get; set; }
        public Nullable<bool> Needworkflow { get; set; }
        public Nullable<bool> CheckConcurrency { get; set; }
        public Nullable<decimal> BookCost { get; set; }
        public Nullable<decimal> FineCharge { get; set; }
        public Nullable<int> PublishedYear { get; set; }
        public string Rack { get; set; }
        public string UploadBook { get; set; }
        public Nullable<int> DocSize { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBookedResource> tblBookedResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEResourceAuthorization> tblEResourceAuthorizations { get; set; }
    }
}
