//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEFormDemo
    {
        public int EFormId { get; set; }
        public string EFormName { get; set; }
        public string Keyword { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<int> AuthorityLevel { get; set; }
        public Nullable<bool> IsAnApprovalForm { get; set; }
        public Nullable<bool> SelfApproval { get; set; }
        public Nullable<int> MetricId { get; set; }
        public string MetricName { get; set; }
        public string MetricFrom { get; set; }
        public string MetricTo { get; set; }
        public Nullable<int> MetriclevelOfAuthority { get; set; }
        public Nullable<int> MetricCategoryId { get; set; }
        public string MetricCategoryname { get; set; }
        public string MetricCategoryFrom { get; set; }
        public string MetricCategoryTo { get; set; }
        public Nullable<int> MetricCategoryLevelOfAuthority { get; set; }
        public Nullable<int> EformType { get; set; }
        public string EformTypeDesc { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
