//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExternalUserExtension_Heritage
    {
        public int ExternalUserExtensionId { get; set; }
        public int InstanceId { get; set; }
        public int UserId { get; set; }
        public string RegNo { get; set; }
        public int PreferredWalkInCenterId { get; set; }
        public int FunctionalAreaId { get; set; }
        public string MaritalStatus { get; set; }
        public string CurrentEmployer { get; set; }
        public string CurrentGrade { get; set; }
        public string CurrentSalary { get; set; }
        public string NoofChildren { get; set; }
        public Nullable<bool> AppliedHeritageEarlier { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public Nullable<int> AppliedBranch { get; set; }
        public string ExpectedJoinDate { get; set; }
        public Nullable<int> TotalExpYears { get; set; }
        public Nullable<int> TotalExpMonths { get; set; }
        public Nullable<int> TeachingExpYears { get; set; }
        public Nullable<int> TeachingExpMonths { get; set; }
        public Nullable<int> AdminExpYears { get; set; }
        public Nullable<int> AdminExpMonths { get; set; }
        public Nullable<int> OtherExpYears { get; set; }
        public Nullable<int> OtherExpMonths { get; set; }
        public string PermanentAddressLine1 { get; set; }
        public string PermanentAddressLine2 { get; set; }
        public Nullable<int> PremanentCountryId { get; set; }
        public Nullable<int> PermanentStateId { get; set; }
        public string PermanentCity { get; set; }
        public string PermanentZip { get; set; }
        public bool FullorQuick { get; set; }
        public Nullable<bool> CriteriaFlag { get; set; }
        public string Resume { get; set; }
        public string WorkSample { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public string DARollNo { get; set; }
        public Nullable<int> AcademicYearID { get; set; }
        public Nullable<bool> IsOtherFunArea { get; set; }
        public Nullable<int> OtherFunAreaValue { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string PanCardNo { get; set; }
        public string PassPortNo { get; set; }
        public Nullable<int> OpeningInfo { get; set; }
        public Nullable<int> PortalUserId { get; set; }
        public Nullable<int> MovedPPL { get; set; }
        public Nullable<System.DateTime> ExpectedDOJ { get; set; }
        public string PersonTagging { get; set; }
        public string TimeTagging { get; set; }
        public string VacancyId { get; set; }
        public string VacancyRaisedBy { get; set; }
    }
}
