//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEFormActivity
    {
        public int EFormActivityId { get; set; }
        public int EFormId { get; set; }
        public int StudentId { get; set; }
        public string EFormDocument { get; set; }
        public Nullable<double> DocSize { get; set; }
        public Nullable<int> SubmittedTo { get; set; }
        public Nullable<int> StatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    
        public virtual tblEForm tblEForm { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
