//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblENotice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblENotice()
        {
            this.tblENoticeAcknowledgements = new HashSet<tblENoticeAcknowledgement>();
            this.tblENoticeTargets = new HashSet<tblENoticeTarget>();
        }
    
        public int ENoticeId { get; set; }
        public int InstanceId { get; set; }
        public int ENoticeTypeId { get; set; }
        public string Subject { get; set; }
        public string ENoticeDescription { get; set; }
        public string NoticeDocument { get; set; }
        public Nullable<double> DocSize { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string DisplayIcon { get; set; }
        public Nullable<bool> SendSMS { get; set; }
        public Nullable<bool> SendEMail { get; set; }
        public Nullable<bool> IncludeParents { get; set; }
        public Nullable<bool> ShowInLogin { get; set; }
        public Nullable<int> IsSMSTemplate { get; set; }
        public Nullable<int> TemplateMasterFK { get; set; }
        public Nullable<bool> IsGlobalNotice { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblENoticeAcknowledgement> tblENoticeAcknowledgements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblENoticeTarget> tblENoticeTargets { get; set; }
    }
}
