//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEFolderDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEFolderDocument()
        {
            this.tblEFolderDocAuthorizations = new HashSet<tblEFolderDocAuthorization>();
        }
    
        public int EFolderDocumentId { get; set; }
        public Nullable<int> FolderId { get; set; }
        public string DocumentName { get; set; }
        public string DocumentDescription { get; set; }
        public double DocumentSize { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public string LockedBy { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEFolderDocAuthorization> tblEFolderDocAuthorizations { get; set; }
        public virtual tblEFolderHeirarchy tblEFolderHeirarchy { get; set; }
    }
}
