//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExamStatu
    {
        public int StatusId { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Points { get; set; }
        public Nullable<int> InstanceId { get; set; }
        public Nullable<int> InstanceSubjectId { get; set; }
        public Nullable<int> GradePointScaleTypeId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Deleteflag { get; set; }
    }
}
