//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExamNotAttemptedReason
    {
        public int ExamNotAttemptedReasonsId { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public string IPAddress { get; set; }
        public string MobileNumber { get; set; }
        public string EmailId { get; set; }
        public string Reason { get; set; }
        public Nullable<int> ActionTaken { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeleteFlag { get; set; }
    }
}
