//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFileManagement
    {
        public int FileId { get; set; }
        public int InstanceId { get; set; }
        public int DepartmentId { get; set; }
        public string FileNumber { get; set; }
        public string FileName { get; set; }
        public string DocName { get; set; }
        public Nullable<int> DocSize { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string Remarks { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
