//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeeInstallments_delete
    {
        public int InstallmentIddelete { get; set; }
        public Nullable<int> InstallmentId { get; set; }
        public int InstanceId { get; set; }
        public Nullable<int> ReceiptNo { get; set; }
        public string InstallmentName { get; set; }
        public int UserFeeId { get; set; }
        public int FeeTypeId { get; set; }
        public int AcademicYearId { get; set; }
        public int FeeTermId { get; set; }
        public Nullable<int> BankAccountId { get; set; }
        public int PaymentModeId { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public string ChequeDDNo { get; set; }
        public Nullable<System.DateTime> ChequeDDDate { get; set; }
        public string ChequeDDBank { get; set; }
        public string ChequeDDBranch { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> CancelReceiptNo { get; set; }
        public Nullable<bool> TransactionCancel { get; set; }
        public Nullable<int> PayableBranchId { get; set; }
        public string CCDDNo { get; set; }
        public string CCDDNameOfCard { get; set; }
        public string CCDDType { get; set; }
        public string CCDDNameofIssuer { get; set; }
        public string BankAddress { get; set; }
        public string AdsComments { get; set; }
    }
}
