//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeeTypeTerm
    {
        public int FeeTypeTermId { get; set; }
        public Nullable<int> InstanceId { get; set; }
        public Nullable<int> AcademicYearId { get; set; }
        public Nullable<int> FeeTermId { get; set; }
        public Nullable<int> FeeTypeId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
