//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFacultyPublication
    {
        public int PublicationId { get; set; }
        public int InstanceId { get; set; }
        public int UserId { get; set; }
        public int PublicationTypeId { get; set; }
        public string PublicationTitle { get; set; }
        public int PublicationLevelId { get; set; }
        public System.DateTime PublicationDate { get; set; }
        public string PublisherName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
