//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGlobalFeeTypesCC
    {
        public int GlobalFeeTypeId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int AcademicYearId { get; set; }
        public int InstanceTypeId { get; set; }
        public byte FeeTypeId { get; set; }
        public byte GST { get; set; }
        public string FeeName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDepositType { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public int HeadQuartersId { get; set; }
        public bool IsEditable { get; set; }
    }
}
