//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHealthhistory
    {
        public int HealthId { get; set; }
        public int Userid { get; set; }
        public int InstanceId { get; set; }
        public int AcademicYearId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string BP { get; set; }
        public string Pulse { get; set; }
        public string VisionL { get; set; }
        public string VisionR { get; set; }
        public string Squint { get; set; }
        public string Conjunctiva { get; set; }
        public string Cornea { get; set; }
        public string EarL { get; set; }
        public string EarR { get; set; }
        public int Createdby { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Deleteflag { get; set; }
        public Nullable<int> RegistrationUserId { get; set; }
    }
}
