//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHealthDetail
    {
        public int HelathDetailsId { get; set; }
        public int InstanceId { get; set; }
        public int UserId { get; set; }
        public int AcademinYearId { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string BloodPressure { get; set; }
        public string Pulse { get; set; }
        public string Pallor { get; set; }
        public string HealthCondition { get; set; }
        public string VisionL { get; set; }
        public string VisionR { get; set; }
        public string Squint { get; set; }
        public string EyeCondition { get; set; }
        public string DentalCondition { get; set; }
        public string Comments { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
