//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstanceClassificationVacancies_Admission
    {
        public int VacancyID { get; set; }
        public Nullable<int> InstanceId { get; set; }
        public Nullable<int> AcademicYearId { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<int> InstanceClassificationId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> NoOfVacancies { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> AgeMonths { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> OnlineTestRequired { get; set; }
        public Nullable<System.DateTime> EndDOB { get; set; }
        public Nullable<int> IsDisplay { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
