//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstance
    {
        public int InstanceId { get; set; }
        public Nullable<int> UniversityId { get; set; }
        public string InstanceName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneExtension { get; set; }
        public string Fax { get; set; }
        public Nullable<int> YearEstablished { get; set; }
        public Nullable<int> ParentInstanceId { get; set; }
        public int LocationId { get; set; }
        public int MasterTypeId { get; set; }
        public string Aboutus { get; set; }
        public string Contactus { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ClassificationName { get; set; }
        public string SubClassificationName { get; set; }
        public string InstanceType { get; set; }
        public byte AttendanceMode { get; set; }
        public string SubDomineName { get; set; }
        public Nullable<int> InstancePeriodsCount { get; set; }
        public string InstanceCode { get; set; }
        public string staffcode { get; set; }
        public string PageName { get; set; }
        public string Url { get; set; }
        public string PlaceForTcandBc { get; set; }
        public string BCFormat { get; set; }
        public string Branch { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<bool> IsBioMetric { get; set; }
        public Nullable<int> BioMetricId { get; set; }
        public Nullable<int> LOPConsideration { get; set; }
        public string CentreERPCode { get; set; }
        public string StudentERPCode { get; set; }
        public string CompanyName { get; set; }
        public string ProgramType { get; set; }
        public string CenterName { get; set; }
        public string STNo { get; set; }
        public string OfficeCode { get; set; }
        public string EnquiryPrefixNo { get; set; }
        public string Company { get; set; }
        public string CentreCode { get; set; }
        public Nullable<int> HubName { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> EntityName { get; set; }
        public Nullable<System.DateTime> IncorprotatedOn { get; set; }
        public Nullable<int> CentreType { get; set; }
        public string Status { get; set; }
        public string City { get; set; }
        public string KRAName { get; set; }
        public string KPIName { get; set; }
        public Nullable<int> DontAllowLogin { get; set; }
        public string EmaiId { get; set; }
    }
}
