//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstanceSalaryAttribute
    {
        public int InstanceSalaryAttributeId { get; set; }
        public int InstanceId { get; set; }
        public int SalaryAttributeMasterId { get; set; }
        public Nullable<int> SalaryAttributeType { get; set; }
        public string SalaryAttributeName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> isLossofpaydedication { get; set; }
        public Nullable<int> SalDependsOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<bool> IsAgainstAdvance { get; set; }
        public Nullable<byte> EligibilityAmount { get; set; }
        public string RelationId { get; set; }
        public Nullable<int> SeqOrder { get; set; }
        public Nullable<bool> Isdebectedlessdays { get; set; }
    }
}
