//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstanceRounds_Admission
    {
        public int RoundID { get; set; }
        public int InstanceID { get; set; }
        public string RoundName { get; set; }
        public string Description { get; set; }
        public int RoundOrder { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpDatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
