//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstanceQuestion
    {
        public int InstanceQuestionId { get; set; }
        public string CategoryId { get; set; }
        public int InstanceId { get; set; }
        public string Question { get; set; }
        public string Description { get; set; }
        public string DocumentName { get; set; }
        public Nullable<double> DocSize { get; set; }
        public Nullable<int> AssignedToId { get; set; }
        public Nullable<bool> IsPrivate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> SubClassficationID { get; set; }
        public Nullable<int> VideoID { get; set; }
        public Nullable<bool> ISGenralQuestion { get; set; }
    }
}
