//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstanceLevel
    {
        public int LevelID { get; set; }
        public int InstanceID { get; set; }
        public int ModuleID { get; set; }
        public string LevelName { get; set; }
        public string LevelShortName { get; set; }
        public string LevelDisplayName { get; set; }
        public Nullable<int> LevelOrder { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
