//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstanceSubjects_bomma
    {
        public int InstanceSubjectId { get; set; }
        public int InstanceId { get; set; }
        public int ClassificationId { get; set; }
        public Nullable<int> SubClassificationId { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> SubjectTypeId { get; set; }
        public string SubjectCode { get; set; }
        public Nullable<bool> IsInternal { get; set; }
        public Nullable<int> TeachedById { get; set; }
        public Nullable<int> AttendanceRequired { get; set; }
        public bool IncludeInTotal { get; set; }
        public Nullable<int> SubjectsDisplayOrder { get; set; }
        public Nullable<int> TotalPeriods { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
