//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstanceAcademicYear
    {
        public int AcademicYearId { get; set; }
        public int InstanceId { get; set; }
        public string Years { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> PreviousAcademicyearId { get; set; }
        public int PaymentModeId { get; set; }
        public Nullable<int> AttendanceModeId { get; set; }
        public Nullable<int> HealthCheckUpsModeId { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<bool> LeaveYearFlag { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<int> InvoiceStartNo { get; set; }
        public Nullable<int> ReceiptStartNo { get; set; }
    }
}
