//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstanceStudentQuestion
    {
        public int InstanceQuestionID { get; set; }
        public Nullable<int> Instanceid { get; set; }
        public string Question { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<int> OnlineTestID { get; set; }
        public Nullable<int> IsPRivate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
