//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstanceRequisition
    {
        public int RequestID { get; set; }
        public int InstanceID { get; set; }
        public int UserID { get; set; }
        public int DeptId { get; set; }
        public string ActivityName { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime Todate { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public Nullable<int> NoOfUsers { get; set; }
        public Nullable<int> NoOfStaff { get; set; }
        public string ActivityPlace { get; set; }
        public string FileAttached { get; set; }
        public Nullable<bool> IsInitialized { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
