//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstanceColumn
    {
        public int InstanceId { get; set; }
        public int Id { get; set; }
        public Nullable<bool> UpdateUserDetails { get; set; }
        public string AssignFor { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public int lInstanceColumnsId { get; set; }
    }
}
