//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstanceBankAccount
    {
        public int BankAccountId { get; set; }
        public int InstanceId { get; set; }
        public string AccountNumber { get; set; }
        public string BankName { get; set; }
        public string Description { get; set; }
        public string BankShortCode { get; set; }
        public string Address { get; set; }
        public string BranchCode { get; set; }
        public string IFCCode { get; set; }
        public Nullable<bool> IsBankTransfer { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
