//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstanceRating
    {
        public int RatingId { get; set; }
        public int InstanceId { get; set; }
        public int RatingTypeId { get; set; }
        public string RatingName { get; set; }
        public int StartingRange { get; set; }
        public int EndingRange { get; set; }
        public string Description { get; set; }
        public Nullable<int> CCEClassRating { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> MasterRatingId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> CurrentRatingId { get; set; }
    }
}
