//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstanceFeeType
    {
        public int FeeTypeId { get; set; }
        public int InstanceId { get; set; }
        public string FeeType { get; set; }
        public string Description { get; set; }
        public Nullable<bool> FeeTypeStatus { get; set; }
        public Nullable<bool> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ReceiptCode { get; set; }
        public Nullable<int> ReceiptNoFrom { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<int> FeeTypeOrder { get; set; }
    }
}
