//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstanceAttendanceType
    {
        public int AttendanceTypeId { get; set; }
        public Nullable<int> InstanceId { get; set; }
        public string AttendanceType { get; set; }
        public string AttendanceTypeDescription { get; set; }
        public Nullable<byte> Value { get; set; }
        public Nullable<bool> Ispresent { get; set; }
        public Nullable<bool> IsAvailableforApply { get; set; }
        public Nullable<int> DisplyOrder { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<bool> SMSFlag { get; set; }
    }
}
