//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKeyResponsibleArea
    {
        public int KeyResponsibleAreaID { get; set; }
        public Nullable<int> FocusAreaID { get; set; }
        public string KRAName { get; set; }
        public Nullable<bool> ISKPI { get; set; }
        public Nullable<int> Marks { get; set; }
        public Nullable<int> ParentKRAID { get; set; }
        public Nullable<int> NoofKPIs { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
