//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLessonPlanExecution
    {
        public int LessonPlanExecutionID { get; set; }
        public int LessonPlanId { get; set; }
        public System.DateTime ExecutionDate { get; set; }
        public string Period { get; set; }
        public string PortionCovered { get; set; }
        public Nullable<int> FacultyID { get; set; }
        public Nullable<bool> ShortFallIfAny { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
