//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogonAudit
    {
        public int LogonAuditId { get; set; }
        public Nullable<int> InstanceId { get; set; }
        public string UserName { get; set; }
        public string IPAddress { get; set; }
        public string URL { get; set; }
        public int LoginAttempt { get; set; }
        public bool LoginStatus { get; set; }
        public string MacAddress { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<int> LoginDetailsStatus { get; set; }
        public string Comments { get; set; }
    }
}
