//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasterRoundStatu
    {
        public int MasterRoundStatusId { get; set; }
        public string MasterRoundStatusName { get; set; }
        public string MasterRoundStatusDescription { get; set; }
        public string comments { get; set; }
        public string MasterRoundStatusCode { get; set; }
    }
}
