//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOnlineTestQuestionnaireAnswersLatest
    {
        public int AnswerId { get; set; }
        public int InstanceId { get; set; }
        public int QuestionnaireId { get; set; }
        public int AnswerMode { get; set; }
        public string AnswerText { get; set; }
        public bool AnswerIsCorrect { get; set; }
        public string AnswerFileName { get; set; }
        public string AnswerFileSize { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public string TranslateAnswerText { get; set; }
    }
}
