//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOfficeAdmin
    {
        public int OfficeId { get; set; }
        public int InstanceId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> DateofResignation { get; set; }
        public Nullable<System.DateTime> DateofServed { get; set; }
        public System.DateTime DateofRelieving { get; set; }
        public Nullable<System.DateTime> LastDateofService { get; set; }
        public string DesignationonLastDate { get; set; }
        public Nullable<bool> RelievedorDiscontinued { get; set; }
        public Nullable<System.DateTime> DateofServingofWarningNotice { get; set; }
        public Nullable<System.DateTime> DateFromDiscontinuedService { get; set; }
        public Nullable<bool> WhetherRelievedProperly { get; set; }
        public Nullable<bool> WhetherRelievedImmediatelyAfterService { get; set; }
        public Nullable<bool> WhetherRelievedAfterLongGap { get; set; }
        public Nullable<bool> WhetherRelievedorNotasonDate { get; set; }
        public string RelievingComments { get; set; }
        public Nullable<bool> IS_Initialized { get; set; }
        public Nullable<bool> ClearanceCompleted { get; set; }
        public Nullable<int> ReasonForLeaving { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public string LeavingForOtherReason { get; set; }
        public Nullable<int> NoticePeriodInDays { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
    }
}
