//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOnlinetestSetDetail
    {
        public int setDetailsId { get; set; }
        public int OnlinetestId { get; set; }
        public int OnlinetestSetId { get; set; }
        public int QuestionnaireId { get; set; }
        public int SetQuestionDisplayOrder { get; set; }
        public int SetAnswerDisplayOrder { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<int> Deleteby { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    }
}
