//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOnlineTestInstanceTopic
    {
        public int TopicId { get; set; }
        public Nullable<int> InstanceId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> OnlineTestId { get; set; }
        public Nullable<int> ClassisficationId { get; set; }
        public Nullable<int> SubClassisficationId { get; set; }
        public Nullable<System.DateTime> TopicDate { get; set; }
        public string AudioFileName { get; set; }
        public Nullable<double> AudioFileSize { get; set; }
        public Nullable<double> AudioTopicMarks { get; set; }
        public Nullable<double> AudioTopicMaxMarks { get; set; }
        public string VideoFileName { get; set; }
        public Nullable<double> VideoFileSize { get; set; }
        public Nullable<double> VideoTopicMarks { get; set; }
        public Nullable<double> VideoTopicMaxMarks { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
