//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOnlinetestQuestionBank
    {
        public int QuestionBankId { get; set; }
        public int InstanceId { get; set; }
        public int InstanceAcademicYearId { get; set; }
        public Nullable<int> InstanceClassificationId { get; set; }
        public Nullable<int> InstanceSubClassificationId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public string QuestionBankName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
