//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOnlinetestDetailsLatest
    {
        public int OnlinetestDetailsId { get; set; }
        public int OnlinetestId { get; set; }
        public int QuestionBankId { get; set; }
        public int TopicId { get; set; }
        public int ChapterId { get; set; }
        public Nullable<int> QuestionComplexityId { get; set; }
        public Nullable<int> NumberofQuestions { get; set; }
        public Nullable<int> Low { get; set; }
        public Nullable<int> Medium { get; set; }
        public Nullable<int> High { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<double> Marks { get; set; }
    }
}
