//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOnlineTestQuestionnaireAnswer
    {
        public int OnlineTestQuestionnaireAnswerId { get; set; }
        public int InstanceId { get; set; }
        public int QuestionId { get; set; }
        public Nullable<int> AnswerMode { get; set; }
        public string AnswerText { get; set; }
        public Nullable<bool> AnswerIsCorrect { get; set; }
        public string AnswerFileName { get; set; }
        public string AnswerFileSize { get; set; }
        public decimal CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
