//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOnlinetestLatest
    {
        public int OnlineTestId { get; set; }
        public int InstanceId { get; set; }
        public int NatureofTest { get; set; }
        public int OnlineTestTypeId { get; set; }
        public string Title { get; set; }
        public double Marks { get; set; }
        public Nullable<int> IsRandomQuestionsFrom { get; set; }
        public Nullable<bool> IsRandomAnswers { get; set; }
        public Nullable<int> DisplayResultsPerQuestion { get; set; }
        public Nullable<int> DisplayIncorrect { get; set; }
        public Nullable<int> Noofattemptsallowed { get; set; }
        public Nullable<bool> IsBackOption { get; set; }
        public Nullable<bool> IsNegativeMarking { get; set; }
        public Nullable<bool> IsAnswerMust { get; set; }
        public Nullable<int> OnlineTestMarksTypeId { get; set; }
        public Nullable<bool> IsHeader { get; set; }
        public string HeaderText { get; set; }
        public string LogoName { get; set; }
        public Nullable<double> Logosize { get; set; }
        public Nullable<int> ExamId { get; set; }
        public Nullable<int> globalSubjectId { get; set; }
        public Nullable<bool> IsAuthorize { get; set; }
        public Nullable<int> SlotBooking { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> ClassificationId { get; set; }
        public Nullable<int> SubClassificationId { get; set; }
        public Nullable<int> IsTheory { get; set; }
        public Nullable<int> ReferenceTheoryIdForPractical { get; set; }
        public Nullable<int> IsRandomQuestionUserWise { get; set; }
        public Nullable<int> GraceTime { get; set; }
    }
}
