//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrientation
    {
        public int OrientationId { get; set; }
        public int InstanceId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string MobilePhone { get; set; }
        public string HomePhone { get; set; }
        public string AlternateMobile { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> deleteFlag { get; set; }
    }
}
