//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOnlineTestRandomQuestionsByUserid
    {
        public int RandomQuestionId { get; set; }
        public Nullable<int> Questionnaireid { get; set; }
        public Nullable<int> InstanceId { get; set; }
        public string Question { get; set; }
        public string QuestionFileName { get; set; }
        public Nullable<double> QuestionFileSize { get; set; }
        public Nullable<int> QuestionComplexityId { get; set; }
        public Nullable<int> QuestionPriority { get; set; }
        public Nullable<int> ParentQuestionId { get; set; }
        public Nullable<int> ModeOfQuestion { get; set; }
        public Nullable<bool> IsMandatory { get; set; }
        public Nullable<bool> IsNestedType { get; set; }
        public Nullable<int> NumberOfNestedQuestions { get; set; }
        public Nullable<double> Marks { get; set; }
        public Nullable<int> OnlinetestSetId { get; set; }
        public Nullable<int> QuestionBankId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TestAuthId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
