//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOverriddenTimeTable
    {
        public int OverriddenTimeTableId { get; set; }
        public System.DateTime OverriddenDate { get; set; }
        public int PeriodId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public int FacultyId { get; set; }
        public Nullable<int> ClassificationId { get; set; }
        public int SubClassificationId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
