//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParent
    {
        public int UserId { get; set; }
        public int InstanceId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> ChangePwOnLogin { get; set; }
        public Nullable<int> SecurityQuestionId { get; set; }
        public string Answer { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> OccupationId { get; set; }
        public string Qualification { get; set; }
        public string AnnualIncome { get; set; }
        public Nullable<int> CurrencyType { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string MobilePhone { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string WorkPhoneExtension { get; set; }
        public string FaxNumber { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string OtherState { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string PAddress1 { get; set; }
        public string PAddress2 { get; set; }
        public Nullable<int> PCountryId { get; set; }
        public Nullable<int> PStateId { get; set; }
        public string POtherState { get; set; }
        public string PCity { get; set; }
        public string PZip { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public Nullable<bool> SendSMS { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Photo { get; set; }
        public Nullable<double> PhotoSize { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<int> Age { get; set; }
        public string FatherHealthStatus { get; set; }
        public string FatherDieteryNeeds { get; set; }
        public string Marriage { get; set; }
        public Nullable<int> BloodGroup { get; set; }
        public string FatherOtherHealthStatus { get; set; }
        public string ParentOfficeAddress1 { get; set; }
        public string ParentOfficeAddress2 { get; set; }
        public Nullable<int> ParentOfficeCountryId { get; set; }
        public Nullable<int> ParentOfficeStateId { get; set; }
        public string ParentOfficeOtherState { get; set; }
        public string ParentOfficeCity { get; set; }
        public string ParentOfficeZip { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> MailingSectorId { get; set; }
        public Nullable<int> PermanentSectorId { get; set; }
        public Nullable<int> OfficeSectorId { get; set; }
        public string Designation { get; set; }
        public string ProfileUpdates { get; set; }
        public string Specialization { get; set; }
        public string Contribution { get; set; }
        public string ProfTechQual { get; set; }
        public string RelEmergencycontact { get; set; }
        public string NeighbourEmergencycontact { get; set; }
        public string DeviceID { get; set; }
    }
}
