//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlacementRound
    {
        public int PlacementRoundId { get; set; }
        public Nullable<int> PlacementProcessId { get; set; }
        public string RoundName { get; set; }
        public string RoundDescription { get; set; }
        public Nullable<int> CoordinatorIds { get; set; }
        public Nullable<int> HRSubordinatorId { get; set; }
        public string ExamPaperName { get; set; }
        public string VenueDetails { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
