//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRIFormSubmittedDemo
    {
        public int RIFormSubmittedDemoID { get; set; }
        public Nullable<int> EFormId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public string ExpenceType { get; set; }
        public Nullable<int> ExpenceID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public Nullable<int> SubmittedToMe { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> LevelOfApproval { get; set; }
        public Nullable<int> EformType { get; set; }
        public string AFENOCC { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
