//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRequestIssuedDetail
    {
        public int IssuedDetailsID { get; set; }
        public int RequisitionStatusID { get; set; }
        public int InstanceId { get; set; }
        public int Status { get; set; }
        public int Quantity { get; set; }
        public string Amount { get; set; }
        public string Damages { get; set; }
        public System.DateTime IssuedOn { get; set; }
        public string IssuedBy { get; set; }
        public string IssuedTo { get; set; }
        public string ReportingforTransportFromTime { get; set; }
        public string ReportingforTransportToTime { get; set; }
        public string DurationTransportRequiredFrom { get; set; }
        public string DurationTransportRequiredTo { get; set; }
        public string TransportRouteFrom { get; set; }
        public string TransportRouteTo { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public string ItemName { get; set; }
        public string Discription { get; set; }
    }
}
