//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegusers_Passwords_52Users
    {
        public int ExtRegistrationUserId { get; set; }
        public int RegistrationUserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int AcademicYearId { get; set; }
        public Nullable<int> ClassificationId { get; set; }
        public Nullable<int> SubClassificationId { get; set; }
        public Nullable<int> Category { get; set; }
        public string AboutChild { get; set; }
        public Nullable<int> Years { get; set; }
        public Nullable<int> Months { get; set; }
        public string LastSchoolPlace { get; set; }
        public string EmailId { get; set; }
        public Nullable<decimal> AnnualIncome { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> CSectorID { get; set; }
        public string PermanentAddressLine1 { get; set; }
        public string PCity { get; set; }
        public Nullable<int> PCountry { get; set; }
        public Nullable<int> PState { get; set; }
        public string PZip { get; set; }
        public Nullable<int> PSectorID { get; set; }
        public Nullable<int> NoOfSiblings { get; set; }
        public string SiblingAges { get; set; }
        public string SiblingSchool { get; set; }
        public string AtHeritageSiblingName { get; set; }
        public string AtHeritageSiblingClass { get; set; }
        public string FamilySituation { get; set; }
        public string FatherSchoolAtmosphere { get; set; }
        public string MotherSchoolAtmosphere { get; set; }
        public string EducationType { get; set; }
        public string TimespentwithChild { get; set; }
        public string BirthCertificate { get; set; }
        public string AddressProof { get; set; }
        public string IncomeProof { get; set; }
        public string AdmissionNo { get; set; }
        public string Gender { get; set; }
        public string LanguageSpoken1 { get; set; }
        public string LanguageSpoken2 { get; set; }
        public string LanguageSpoken3 { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> MotherTongueId { get; set; }
        public string ResidentialPhone { get; set; }
        public string ReasonforLeaving { get; set; }
        public Nullable<System.DateTime> PreviousSchoolFromDate { get; set; }
        public Nullable<System.DateTime> PreviousSchoolToDate { get; set; }
        public string PreviousSchoolTown { get; set; }
        public string PreviousSchoolAffliatedTo { get; set; }
        public string PreviousSchoolMedium { get; set; }
        public Nullable<System.DateTime> CertificatesSupplyDate { get; set; }
        public Nullable<int> CampusApplied { get; set; }
        public Nullable<int> RegisteredBy { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<double> PhotoSize { get; set; }
        public string Photo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> ModeOFPayment { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> DateOFAdmission { get; set; }
        public Nullable<int> Criteria { get; set; }
        public Nullable<int> ReferredBy { get; set; }
        public Nullable<int> IsMassTerm { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public string DevelopmentalDelay { get; set; }
        public string ChildComplications { get; set; }
        public string PostComplications { get; set; }
        public string Convulsions { get; set; }
        public string CrawlingCheck { get; set; }
        public string SittingCheck { get; set; }
        public string WalkingCheck { get; set; }
        public string StandingCheck { get; set; }
        public string VocalisationCheck { get; set; }
        public string BabblingCheck { get; set; }
        public string OneWordCheck { get; set; }
        public string OneSentenceCheck { get; set; }
        public string CrawlingRemarks { get; set; }
        public string SittingRemarks { get; set; }
        public string WalkingRemarks { get; set; }
        public string StandingRemarks { get; set; }
        public string VocalisationRemarks { get; set; }
        public string BabblingRemarks { get; set; }
        public string OneWordRemarks { get; set; }
        public string OneSentenceRemarks { get; set; }
        public string PrevSchoolDuration { get; set; }
        public string IndividualSupport { get; set; }
        public string SpecificInterventions { get; set; }
        public string ProvisionalAdmissionNo { get; set; }
        public Nullable<System.DateTime> ChequeDDDate { get; set; }
        public string ChequebankName { get; set; }
        public Nullable<int> PayableBranchID { get; set; }
        public Nullable<System.DateTime> ExpectedDateOfjoining { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string TransferCertificate { get; set; }
        public string LastReport { get; set; }
        public Nullable<bool> IsTwinSiblingApplied { get; set; }
        public string SiblingRegistrationNumber { get; set; }
        public string StaffId { get; set; }
        public string OtherCitySector { get; set; }
        public Nullable<bool> IsAdmissionLinkSent { get; set; }
        public Nullable<System.DateTime> LinkLastDate { get; set; }
    }
}
