//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoute
    {
        public int RouteId { get; set; }
        public int InstanceId { get; set; }
        public string RouteName { get; set; }
        public string BusNo { get; set; }
        public Nullable<bool> BusType { get; set; }
        public string StartingPoint { get; set; }
        public string StartTime { get; set; }
        public string RouteDescription { get; set; }
        public string StartPoint { get; set; }
        public string EndPoint { get; set; }
        public string RouteLength { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<int> InchargeId { get; set; }
    }
}
