//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegistrationUserDetail
    {
        public int RegistrationUserId { get; set; }
        public Nullable<int> InstanceId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Age { get; set; }
        public string PlaceOfBirth { get; set; }
        public string AdmissionForClass { get; set; }
        public string PreviousSchool { get; set; }
        public string PreviousClass { get; set; }
        public string FatherName { get; set; }
        public string FatherQualification { get; set; }
        public string FatherOccupation { get; set; }
        public string FatherDesignation { get; set; }
        public Nullable<int> FatherServiceYears { get; set; }
        public string MotherName { get; set; }
        public string MotherQualification { get; set; }
        public string MotherOccupation { get; set; }
        public string MotherDesignation { get; set; }
        public string ParentMobileNumber { get; set; }
        public string ParentEmail { get; set; }
        public string CaptchaData { get; set; }
        public string RequestPage { get; set; }
        public Nullable<bool> EnquiryAccepted { get; set; }
        public string EnqPersonName { get; set; }
        public string Curriculum { get; set; }
        public string HowDiduKnow { get; set; }
        public string ResourcePersonName { get; set; }
        public Nullable<System.DateTime> PrefInterDate { get; set; }
        public string EnquiryHandledBy { get; set; }
        public Nullable<System.DateTime> AllottedInterDate { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string city { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public string RegistrationNumber { get; set; }
        public string CurriculumnInterested { get; set; }
        public Nullable<System.DateTime> StudentDob { get; set; }
        public Nullable<bool> ISWithdrawan { get; set; }
        public Nullable<System.DateTime> WithdrawanDate { get; set; }
        public string WithdrawanComments { get; set; }
    }
}
