//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRouteStop
    {
        public int StopId { get; set; }
        public Nullable<int> RouteId { get; set; }
        public string StopName { get; set; }
        public string ArrivalTime { get; set; }
        public string DepartureTime { get; set; }
        public Nullable<int> TransportFee { get; set; }
        public Nullable<int> StopOrder { get; set; }
        public string TimeFromPreviousStop { get; set; }
        public string WaitingTime { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
