//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecruitmentBranch
    {
        public int RecruitmentBranchID { get; set; }
        public int InstanceId { get; set; }
        public int BranchId { get; set; }
        public string HQInstanceName { get; set; }
        public string BranchCode { get; set; }
        public string BranchHeadName { get; set; }
        public string BranchHeadEmail { get; set; }
        public string BranchCareerEmail { get; set; }
        public string BranchShuttleService { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> Deleteflag { get; set; }
    }
}
