//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecruitmentRequisition
    {
        public int RecruitmentRequisitionId { get; set; }
        public int InstanceId { get; set; }
        public Nullable<System.DateTime> DateofOpening { get; set; }
        public Nullable<System.DateTime> Requisitionloggedon { get; set; }
        public Nullable<int> Requisitionraisedby { get; set; }
        public Nullable<int> ReasonofRecruitment { get; set; }
        public Nullable<int> TypeofRecruitment { get; set; }
        public Nullable<int> FunctionalArea { get; set; }
        public Nullable<int> Department { get; set; }
        public string SubfunctionalArea { get; set; }
        public string Subject { get; set; }
        public string ClassesPreferred { get; set; }
        public Nullable<int> TotalExperienceRequired { get; set; }
        public string RelevantExperience { get; set; }
        public Nullable<int> DesiredMonth { get; set; }
        public Nullable<int> DesiredYear { get; set; }
        public Nullable<int> AcademicSession { get; set; }
        public string PriorityofRecruitment { get; set; }
        public string Resposibilities { get; set; }
        public string Education { get; set; }
        public Nullable<int> Qualifications { get; set; }
        public string CommunicationsSkills { get; set; }
        public Nullable<int> ReplacementUserId { get; set; }
        public string JobTitle { get; set; }
        public string LeaveVacancy { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<System.DateTime> DateofClosing { get; set; }
        public Nullable<int> SelectedUserId { get; set; }
        public Nullable<int> NoofVacancy { get; set; }
        public Nullable<int> SubClassificationId { get; set; }
    }
}
