//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSkillsofUser_Admission
    {
        public int SkillId { get; set; }
        public int RegistrationUserId { get; set; }
        public string I_A { get; set; }
        public string Closure { get; set; }
        public string Clerical { get; set; }
        public string Mechanical { get; set; }
        public string Numerical { get; set; }
        public string Psychomotor { get; set; }
        public string Reasoning { get; set; }
        public string Spatial { get; set; }
        public string Verbal { get; set; }
        public string WritingSkills { get; set; }
    }
}
