//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStaffwithdrawalStatu
    {
        public int StaffWithdrawalStatusID { get; set; }
        public int InstanceID { get; set; }
        public int OfficeID { get; set; }
        public int ClearanceLevelID { get; set; }
        public int SubmittedUserID { get; set; }
        public int ApproverUserID { get; set; }
        public Nullable<int> DelegatedUserId { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> IsCleared { get; set; }
        public string ClearedComments { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
