//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalaryAttributes_bkp17_MAy_2013
    {
        public int SalaryAttributeId { get; set; }
        public int InstanceId { get; set; }
        public Nullable<int> AuthId { get; set; }
        public int UserId { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string IsSalaryPercentage { get; set; }
        public int InstanceSalaryAttributeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<System.DateTime> StartD { get; set; }
        public Nullable<System.DateTime> EndD { get; set; }
        public Nullable<System.DateTime> UpdatedD { get; set; }
        public Nullable<decimal> UserEligibilityAmount { get; set; }
    }
}
