//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSpouseInfo
    {
        public int SpouseId { get; set; }
        public int UserId { get; set; }
        public int Instanceid { get; set; }
        public string Organization { get; set; }
        public string Occupation { get; set; }
        public string Designation { get; set; }
        public string Transferrablejob { get; set; }
        public string FirstKidAge { get; set; }
        public string FirstKidName { get; set; }
        public string FirstKidSchool { get; set; }
        public string SecondKidAge { get; set; }
        public string SecondKidName { get; set; }
        public string SecondKidSchool { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
