//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScheduledInstance
    {
        public int ScheduledInstanceID { get; set; }
        public Nullable<int> InstanceID { get; set; }
        public Nullable<int> TypeOfSchedule { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<bool> Repeat { get; set; }
        public Nullable<double> RepeatInterval { get; set; }
        public Nullable<int> DaysPrior { get; set; }
        public Nullable<bool> SMSAlert { get; set; }
        public Nullable<bool> EmailAlert { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    
        public virtual tblScheduleType tblScheduleType { get; set; }
    }
}
