//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentObservation
    {
        public int StudentObservationID { get; set; }
        public int InstanceID { get; set; }
        public int AcademicYearID { get; set; }
        public int TermID { get; set; }
        public int StudentID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Time { get; set; }
        public int LocationID { get; set; }
        public string OtherLocation { get; set; }
        public string Context { get; set; }
        public string Objective { get; set; }
        public string Description { get; set; }
        public string Interpretation { get; set; }
        public int IncludeInReports { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
