//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentwithdrawalForm
    {
        public int StudentWithdrawalID { get; set; }
        public int InstanceID { get; set; }
        public int UserID { get; set; }
        public System.DateTime LastDateofAttendance { get; set; }
        public Nullable<System.DateTime> TCIssueDate { get; set; }
        public int LeavingReasonID { get; set; }
        public string LeavingDescription { get; set; }
        public string OtherReason { get; set; }
        public string FeedBack { get; set; }
        public string NewSchoolName { get; set; }
        public Nullable<bool> CancelledFlag { get; set; }
        public Nullable<bool> IsSubmittedByParent { get; set; }
        public Nullable<int> WithdrawalStatusID { get; set; }
        public Nullable<bool> ISVacanceyCreated { get; set; }
        public string Specialrequests { get; set; }
        public string WithdrawalTypeId { get; set; }
        public string FileNameDuesAndRefunds { get; set; }
        public string DuesAndRefundsUploadedBy { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
