//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubjectToolMark
    {
        public int SubjectToolMarksId { get; set; }
        public int ExamSubjectToolId { get; set; }
        public int StudentId { get; set; }
        public Nullable<double> SecuredMarks { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> Ispublished { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<bool> IsReTest { get; set; }
    }
}
