//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSpecialEducationNeed
    {
        public int SpecialEducationID { get; set; }
        public int UserId { get; set; }
        public int AcademicYearId { get; set; }
        public string SpecialEducation { get; set; }
        public string Therapy { get; set; }
        public Nullable<bool> TherapyEnrolled { get; set; }
        public Nullable<System.DateTime> TherapyStartDate { get; set; }
        public Nullable<System.DateTime> TherapyEndDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
