//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSiblingRelationDetails_Admission
    {
        public int SiblingRelationID { get; set; }
        public Nullable<int> RelationtypeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> Age { get; set; }
        public string SchoolName { get; set; }
        public string ClassName { get; set; }
        public string RelationshipwithStudent { get; set; }
        public Nullable<bool> ISSiblingRelation { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> InstanceID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
