//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShiftAllocationForUser
    {
        public int ShiftAllocationID { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<int> AcademicYearID { get; set; }
        public Nullable<int> InstanceID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.TimeSpan> LateComingMins { get; set; }
        public Nullable<System.TimeSpan> EarlyGoingMins { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<bool> Daywise { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DayWiseShiftID { get; set; }
    
        public virtual tblShiftAllocationForUser tblShiftAllocationForUsers1 { get; set; }
        public virtual tblShiftAllocationForUser tblShiftAllocationForUser1 { get; set; }
    }
}
