//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShiftMaster
    {
        public int ShiftID { get; set; }
        public Nullable<int> AcademicYearID { get; set; }
        public Nullable<int> InstanceID { get; set; }
        public string ShiftName { get; set; }
        public Nullable<System.TimeSpan> ShiftInTime { get; set; }
        public Nullable<System.TimeSpan> ShiftOutTime { get; set; }
        public Nullable<bool> MultiplePunches { get; set; }
        public Nullable<System.TimeSpan> MinWorkHrs { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
