//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSmsPlaceHolder
    {
        public int PlaceHolderId { get; set; }
        public int InstanceId { get; set; }
        public string ScreenName { get; set; }
        public string PlaceHolders { get; set; }
    }
}
