//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentWithdrawalExitInterviewForm
    {
        public int ExitInterviewFormID { get; set; }
        public int InstanceID { get; set; }
        public int StudentwithdrawalID { get; set; }
        public string ReasonsFoLeaving { get; set; }
        public string NewSchoolNameCity { get; set; }
        public string DescribeOurSchool { get; set; }
        public string ThingsShouldContinue { get; set; }
        public string ThingsShouldStop { get; set; }
        public string ThingsShouldStart { get; set; }
        public string AnyRecommendation { get; set; }
        public string MovingCityUpdateAddress { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
