//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentWithdrawalClearanceDetail
    {
        public int ClearanceDetailsID { get; set; }
        public Nullable<int> StudentWithdrawalStatusID { get; set; }
        public string ItemName { get; set; }
        public string ItemAmount { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> IssuedReturnedFlag { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
