//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransportation
    {
        public Nullable<int> RouteId { get; set; }
        public Nullable<int> InstanceId { get; set; }
        public string RouteName { get; set; }
        public string StartingPoint { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public int RouteIdPk { get; set; }
    }
}
