//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrainingCentreDetail
    {
        public int TCDetID { get; set; }
        public int TCID { get; set; }
        public int HubID { get; set; }
        public int TotalSqFt { get; set; }
        public Nullable<int> RentalSqFt { get; set; }
        public Nullable<int> DepositAmount { get; set; }
        public System.DateTime AgreementDate { get; set; }
        public int LeaseDuration { get; set; }
        public Nullable<int> Floors { get; set; }
        public Nullable<int> RentalPerMonth { get; set; }
        public Nullable<int> EscalationPersent { get; set; }
        public System.DateTime AgreementExpDate { get; set; }
        public string Directions { get; set; }
        public string RenewalNoticePeriod { get; set; }
        public Nullable<int> ServiceTax { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
