//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaxCaliculation
    {
        public int TaxDetailsId { get; set; }
        public int UserId { get; set; }
        public Nullable<decimal> HRAExemptions { get; set; }
        public Nullable<decimal> PrevPT { get; set; }
        public Nullable<decimal> LossOnHouseProperty { get; set; }
        public Nullable<decimal> IncFromOthersource { get; set; }
        public Nullable<decimal> Elss { get; set; }
        public Nullable<decimal> Lic { get; set; }
        public Nullable<decimal> Nsc { get; set; }
        public Nullable<decimal> Ulip { get; set; }
        public Nullable<decimal> InfraBond { get; set; }
        public Nullable<decimal> PensionPlan { get; set; }
        public Nullable<decimal> PensionPlanMutFund { get; set; }
        public Nullable<decimal> PrevPF { get; set; }
        public Nullable<decimal> HSGLoan { get; set; }
        public Nullable<decimal> TutionFee { get; set; }
        public Nullable<decimal> AnnutyPlan { get; set; }
        public Nullable<decimal> FixedDeposit { get; set; }
        public Nullable<decimal> LongTermInfraBond { get; set; }
        public Nullable<decimal> MedicalIns { get; set; }
        public Nullable<decimal> MTCofHandiDep { get; set; }
        public Nullable<decimal> HandicappedPersons { get; set; }
        public Nullable<decimal> Eduloan { get; set; }
        public Nullable<decimal> TaxPayable { get; set; }
        public Nullable<decimal> RentPaidByEmployee { get; set; }
        public Nullable<decimal> TaxFromPrevEmployer { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
        public Nullable<decimal> ConvExemptions { get; set; }
        public Nullable<decimal> LTAExemptions { get; set; }
        public Nullable<decimal> MedicalExemptions { get; set; }
        public Nullable<decimal> OthersExemptions { get; set; }
        public Nullable<decimal> ProfessionalTax { get; set; }
        public Nullable<decimal> PPF { get; set; }
        public Nullable<decimal> EPF { get; set; }
        public Nullable<decimal> TaxableIncome { get; set; }
        public Nullable<decimal> Educess { get; set; }
        public Nullable<bool> TaxShowtoEmployee { get; set; }
        public Nullable<decimal> FoodCoupons { get; set; }
        public Nullable<decimal> Section80G { get; set; }
        public Nullable<decimal> Section80CCD { get; set; }
        public Nullable<decimal> ReliefUs89 { get; set; }
        public Nullable<bool> IsFinalSubmission { get; set; }
    }
}
