//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTimeTableDetail
    {
        public int TimeTableDetailsId { get; set; }
        public int TimetableId { get; set; }
        public Nullable<int> DayId { get; set; }
        public int PeriodId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpDatedBy { get; set; }
        public Nullable<System.DateTime> UpDatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public string PeriodName { get; set; }
    }
}
