//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransportStatu
    {
        public int TransportStatusId { get; set; }
        public int TransportFormId { get; set; }
        public Nullable<int> AssignedPickUpRouteId { get; set; }
        public Nullable<int> AssignedPickupStopId { get; set; }
        public Nullable<int> AssignedDropRouteId { get; set; }
        public Nullable<int> AssignedDropStopId { get; set; }
        public int StatusId { get; set; }
        public string PickUpWaitListNo { get; set; }
        public string DropWaitListNo { get; set; }
        public Nullable<bool> IsFinalApproved { get; set; }
        public Nullable<bool> IsFeePaid { get; set; }
        public string Comments { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Deleteflag { get; set; }
    }
}
