//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserCompany
    {
        public int UserCompanyId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyURL { get; set; }
        public string CompAddress { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string DesignationDescription { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string RoleDescription { get; set; }
        public Nullable<int> IndustryTypeId { get; set; }
        public string Location { get; set; }
        public string Salary { get; set; }
        public Nullable<int> CurrencyType { get; set; }
        public Nullable<int> JobTypeId { get; set; }
        public Nullable<int> EmploymentStatusId { get; set; }
        public Nullable<int> FunctionalAreaId { get; set; }
        public string ReasonForChange { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
