//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserOnlineTestGeneratedQuestion
    {
        public int GeneratedQuestionID { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> OnlineTestQuestionnaireid { get; set; }
        public Nullable<int> onlinetestid { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> deleteflag { get; set; }
    }
}
