//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserExtension_RIG_ICFE
    {
        public int UserExtensionId { get; set; }
        public int InstanceId { get; set; }
        public int UserId { get; set; }
        public string FatherName { get; set; }
        public string ParentorGurdianMobileNo { get; set; }
        public string ParentorGurdianEmail { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> ComputerLiterate { get; set; }
        public Nullable<int> Presently { get; set; }
        public Nullable<int> MonthlyFamilyIncome { get; set; }
        public Nullable<int> PreferableBatchTimings { get; set; }
        public Nullable<int> IntrestInJobGuarantee { get; set; }
        public string TestCode { get; set; }
        public string TestResults { get; set; }
        public Nullable<int> InterviewedBy { get; set; }
        public Nullable<int> CounselledBy { get; set; }
        public string CounsellorRemarks { get; set; }
        public Nullable<int> BatchId { get; set; }
        public string FriendName { get; set; }
        public string FriendMobileNo { get; set; }
        public string FriendEmailId { get; set; }
        public string FriendName1 { get; set; }
        public string FriendMobileNo1 { get; set; }
        public string FriendEmailId1 { get; set; }
        public Nullable<int> counselorId { get; set; }
        public string HowDouKnowAboutInst { get; set; }
        public string LearnComputerAccounts { get; set; }
        public Nullable<bool> UserStatus { get; set; }
        public Nullable<byte> OfficeIsJobGurantee { get; set; }
        public Nullable<bool> isCurrentlyHandling { get; set; }
        public string CallStatus { get; set; }
        public Nullable<System.DateTime> CallDateTime { get; set; }
        public Nullable<System.DateTime> CallbackDate { get; set; }
        public string Description { get; set; }
        public string StudentQualification { get; set; }
        public string Course { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public Nullable<System.DateTime> DateOfExpiry { get; set; }
        public string Fax { get; set; }
        public string Nationality { get; set; }
        public string EnglishProf { get; set; }
        public string EnglishDegree { get; set; }
        public string Age { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<int> EnquiryDetailsId { get; set; }
        public string ProspectusNumber { get; set; }
    }
}
