//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUseronlinetestDetailsforAdmission
    {
        public int UseronlinetestDetailsId { get; set; }
        public int userid { get; set; }
        public Nullable<int> onlineTestauthid { get; set; }
        public Nullable<int> Onlinetestsequenceid { get; set; }
        public int OnlinetestSetId { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<byte> onlinetestStatus { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<System.DateTime> Duedate { get; set; }
        public Nullable<int> DurationId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public string timetocomplete { get; set; }
        public Nullable<int> NextQuestionCountNo { get; set; }
        public System.DateTime createddate { get; set; }
        public int createdby { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<System.DateTime> deleteddate { get; set; }
        public Nullable<int> deletedby { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
