//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserExtension_bkpHeritage
    {
        public int AdmissionPkId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> InstanceId { get; set; }
        public Nullable<int> AdmissionId { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public Nullable<int> ReservationPKId { get; set; }
        public Nullable<int> SalesOfApplicationId { get; set; }
        public Nullable<int> ReservationId { get; set; }
        public Nullable<int> ReservationAt { get; set; }
        public Nullable<int> ReservationFor { get; set; }
        public Nullable<int> MediumId { get; set; }
        public Nullable<int> StudentTypeId { get; set; }
        public Nullable<int> PackageId { get; set; }
        public string FatherName { get; set; }
        public string FatherOccupation { get; set; }
        public string MotherName { get; set; }
        public string PreviousOrganization { get; set; }
        public string PreviousCourse { get; set; }
        public string PreviousTotalMarks { get; set; }
        public string PreviousHTNo { get; set; }
        public Nullable<bool> ParentSignature { get; set; }
        public Nullable<bool> PrincipalSignature { get; set; }
        public Nullable<bool> DirectorSignature { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> SubCategory { get; set; }
        public Nullable<bool> IsEsi { get; set; }
        public Nullable<bool> IsPF { get; set; }
        public string MaritalStatus { get; set; }
        public string TeachingType { get; set; }
        public string EmployeeReplacewith { get; set; }
        public string EmployeeType { get; set; }
        public string Bank { get; set; }
        public string AccountNo { get; set; }
        public string GrassSalary { get; set; }
        public Nullable<decimal> AnnualSalary { get; set; }
        public Nullable<decimal> BaseSalary { get; set; }
        public Nullable<int> PendingWithLevelId { get; set; }
        public Nullable<int> GlobalClassificationId { get; set; }
        public string CurrentlyPursuingCourse { get; set; }
        public string AreasOfInterest { get; set; }
        public Nullable<int> NoOfProjectsGuiding { get; set; }
        public Nullable<int> IndustryExperience { get; set; }
        public string HighestQuaAttained { get; set; }
        public string TeachingExperience { get; set; }
        public string UniversitySpecialization { get; set; }
        public Nullable<int> YearOfCompletion { get; set; }
        public string ShiftCode { get; set; }
        public string IFSCode { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public string Behaviour { get; set; }
        public string TicsHabits { get; set; }
        public string Sociability { get; set; }
        public string ToiletHabits { get; set; }
        public string Posture { get; set; }
        public string OtherObservations { get; set; }
        public string std { get; set; }
        public string Year { get; set; }
        public string HistoryOFFamilyHealth { get; set; }
        public string HealthRecordofPupil { get; set; }
        public string HistoryOfFrequentillness { get; set; }
        public string Immunisation { get; set; }
        public string OtherFrequentillness { get; set; }
        public Nullable<System.DateTime> WithdrawalDate { get; set; }
        public Nullable<System.DateTime> IncrementDate { get; set; }
        public string PFNO { get; set; }
        public string PANNO { get; set; }
        public Nullable<int> LMSCategory { get; set; }
        public Nullable<int> LMSSubCategory { get; set; }
        public Nullable<int> FeeConceedingTypeId { get; set; }
        public Nullable<int> MailingSectorId { get; set; }
        public Nullable<int> PermanentSectorId { get; set; }
        public string HiredCABRegNo { get; set; }
        public Nullable<int> HiredCABDriverID { get; set; }
        public string CostCenter { get; set; }
        public Nullable<System.DateTime> EffectiveDateofPosition { get; set; }
        public Nullable<int> NoofChildern { get; set; }
        public Nullable<int> Registrationuserid { get; set; }
        public Nullable<int> AdmissionCategory { get; set; }
        public string BioID { get; set; }
    }
}
