//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserExitForm
    {
        public int ExitFormId { get; set; }
        public int InstanceId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> Rating1 { get; set; }
        public Nullable<int> Rating2 { get; set; }
        public Nullable<int> Rating3 { get; set; }
        public Nullable<int> Rating4 { get; set; }
        public Nullable<int> Rating5 { get; set; }
        public Nullable<int> Rating6 { get; set; }
        public Nullable<int> Rating7 { get; set; }
        public Nullable<int> Rating8 { get; set; }
        public Nullable<int> Rating9 { get; set; }
        public Nullable<int> Rating10 { get; set; }
        public Nullable<int> Rating11 { get; set; }
        public Nullable<int> Rating12 { get; set; }
        public Nullable<int> Rating13 { get; set; }
        public Nullable<int> Rating14 { get; set; }
        public Nullable<bool> Reason1Checked { get; set; }
        public Nullable<int> Reason1Rating { get; set; }
        public Nullable<bool> Reason2Checked { get; set; }
        public Nullable<int> Reason2Rating { get; set; }
        public Nullable<bool> Reason3Checked { get; set; }
        public Nullable<int> Reason3Rating { get; set; }
        public Nullable<bool> Reason4Checked { get; set; }
        public Nullable<int> Reason4Rating { get; set; }
        public Nullable<bool> Reason5Checked { get; set; }
        public Nullable<int> Reason5Rating { get; set; }
        public Nullable<bool> Reason6Checked { get; set; }
        public Nullable<int> Reason6Rating { get; set; }
        public Nullable<bool> Reason7Checked { get; set; }
        public Nullable<int> Reason7Rating { get; set; }
        public string OtherReasonsIfAny { get; set; }
        public string ReJoin { get; set; }
        public string HeritageStrengths { get; set; }
        public string AreasHeritageCanBetter { get; set; }
        public string AboutProgramLead { get; set; }
        public string AnyOtherComments { get; set; }
        public Nullable<int> InterviewerUserId { get; set; }
        public string ObservationsBytheInterviewer { get; set; }
        public string EmployeeJoiningOrganization { get; set; }
        public string DesignationOffered { get; set; }
        public string SalaryOffered { get; set; }
        public string SalaryDrawnAtHeritage { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
