//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserBatchStatus_Heritage
    {
        public int UserBatchId { get; set; }
        public int InstanceId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> BatchId { get; set; }
        public int RoundId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> RoundDate { get; set; }
        public string RoundTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<double> Marks { get; set; }
        public Nullable<int> TopicId { get; set; }
        public string RoomNo { get; set; }
        public string Class { get; set; }
        public string Comments { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<bool> OptionToCallBack { get; set; }
        public Nullable<System.DateTime> CallBackDate { get; set; }
        public Nullable<int> DemoCenterID { get; set; }
        public Nullable<double> PassMarks { get; set; }
        public string DocumentName { get; set; }
        public string DemoDoc { get; set; }
        public string DemoTopic { get; set; }
        public string DemoClass { get; set; }
        public string ReportingTime { get; set; }
        public Nullable<System.DateTime> CommitmentFeeDate { get; set; }
        public string InterviewResult { get; set; }
        public string InterviewMode { get; set; }
        public Nullable<int> CourseRollFlag { get; set; }
    }
}
