//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserBatchStatus_Admission
    {
        public int UserBatchID { get; set; }
        public int InstanceID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public int RoundID { get; set; }
        public int StatusID { get; set; }
        public string RoundDate { get; set; }
        public string RoundTime { get; set; }
        public string IsActive { get; set; }
        public Nullable<double> Marks { get; set; }
        public string Comments { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<double> PassMarks { get; set; }
    }
}
