//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSNewDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVaccinationNew_Admission
    {
        public int VaccinationId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Instanceid { get; set; }
        public Nullable<int> AcademicyearId { get; set; }
        public Nullable<System.DateTime> BcgDueDate { get; set; }
        public Nullable<System.DateTime> BcgDate { get; set; }
        public Nullable<System.DateTime> HepatitisBirthDueDate { get; set; }
        public Nullable<System.DateTime> HepatitisBirthDate { get; set; }
        public Nullable<System.DateTime> Hepatitis1MonDueDate { get; set; }
        public Nullable<System.DateTime> Hepatitis1MonDate { get; set; }
        public Nullable<System.DateTime> Hepatitis6MonDueDate { get; set; }
        public Nullable<System.DateTime> Hepatitis6MonDate { get; set; }
        public Nullable<System.DateTime> DPT2MonDueDate { get; set; }
        public Nullable<System.DateTime> DPT2MonDate { get; set; }
        public Nullable<System.DateTime> DPT3MonDueDate { get; set; }
        public Nullable<System.DateTime> DPT3MonDate { get; set; }
        public Nullable<System.DateTime> DPT4MonDueDate { get; set; }
        public Nullable<System.DateTime> DPT4MonDate { get; set; }
        public Nullable<System.DateTime> HB2MonDueDate { get; set; }
        public Nullable<System.DateTime> HB2MonDate { get; set; }
        public Nullable<System.DateTime> HB3MonDueDate { get; set; }
        public Nullable<System.DateTime> HB3MonDate { get; set; }
        public Nullable<System.DateTime> HB4MonDueDate { get; set; }
        public Nullable<System.DateTime> HB4MonDate { get; set; }
        public Nullable<System.DateTime> OralPolioBirthDueDate { get; set; }
        public Nullable<System.DateTime> OralPolioBirthDate { get; set; }
        public Nullable<System.DateTime> OralPolio1MonDueDate { get; set; }
        public Nullable<System.DateTime> OralPolio1MonDate { get; set; }
        public Nullable<System.DateTime> OralPolio2MonDueDate { get; set; }
        public Nullable<System.DateTime> OralPolio2MonDate { get; set; }
        public Nullable<System.DateTime> OralPolio3MonDueDate { get; set; }
        public Nullable<System.DateTime> OralPolio3MonDate { get; set; }
        public Nullable<System.DateTime> OralPolio4MonDueDate { get; set; }
        public Nullable<System.DateTime> OralPolio4MonDate { get; set; }
        public Nullable<System.DateTime> Measles9MonDueDate { get; set; }
        public Nullable<System.DateTime> Measles9MonDate { get; set; }
        public Nullable<System.DateTime> MMR16MonDueDate { get; set; }
        public Nullable<System.DateTime> MMR16MonDate { get; set; }
        public Nullable<System.DateTime> DPTOPV18MonDueDate { get; set; }
        public Nullable<System.DateTime> DPTOPV18MonDate { get; set; }
        public Nullable<System.DateTime> Typhoid2YearsDueDate { get; set; }
        public Nullable<System.DateTime> Typhoid2YearsDate { get; set; }
        public Nullable<System.DateTime> Hepatitis2YearsDueDate { get; set; }
        public Nullable<System.DateTime> Hepatitis2YearsDate { get; set; }
        public Nullable<System.DateTime> ChickenPox1YearsDueDate { get; set; }
        public Nullable<System.DateTime> ChickenPox1YearsDate { get; set; }
        public Nullable<System.DateTime> DTOPA4YearsDueDate { get; set; }
        public Nullable<System.DateTime> DTOPA4YearsDate { get; set; }
        public string TyphoidYears { get; set; }
        public Nullable<System.DateTime> Typhoid3YearsDueDate { get; set; }
        public Nullable<System.DateTime> Typhoid3YearsDate { get; set; }
        public string TT5Years { get; set; }
        public Nullable<System.DateTime> TT5YearsDueDate { get; set; }
        public Nullable<System.DateTime> TT5YearsDate { get; set; }
        public string OtherVaccinesYears { get; set; }
        public Nullable<System.DateTime> OtherVaccinesDueDate { get; set; }
        public Nullable<System.DateTime> OtherVaccinesDate { get; set; }
        public string HeadNeckNormal { get; set; }
        public string HeadNeckDetails { get; set; }
        public string AbdomenNormal { get; set; }
        public string AbdomenDetails { get; set; }
        public string NailsNormal { get; set; }
        public string NailsDetails { get; set; }
        public string HairNormal { get; set; }
        public string HairDetails { get; set; }
        public string SkinNormal { get; set; }
        public string SkinDetails { get; set; }
        public string EarNormal { get; set; }
        public string EarDetails { get; set; }
        public string NoseNormal { get; set; }
        public string NoseDetails { get; set; }
        public string ThroatNormal { get; set; }
        public string ThroatDetails { get; set; }
        public Nullable<int> BloodGroupId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Deleteflag { get; set; }
        public string DoctorName { get; set; }
        public string DoctorDesignation { get; set; }
        public Nullable<System.DateTime> DateOfExamination { get; set; }
        public string RegNoOfDoctor { get; set; }
        public string DoctorMobileNo { get; set; }
        public string DoctorPlace { get; set; }
        public string RegularMedication { get; set; }
        public Nullable<System.DateTime> DateOfPhysicalExam { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string BP { get; set; }
        public string Pulse { get; set; }
        public string Vision_Left { get; set; }
        public string Vision_Right { get; set; }
        public string Squint { get; set; }
        public string Conjectiva { get; set; }
        public string Ear_Left { get; set; }
        public string Ear_Right { get; set; }
        public string AnemiaSpec { get; set; }
        public string CurrentHealthCon { get; set; }
        public string FitPhysicalAct { get; set; }
        public string FitPhysicalPrecaution { get; set; }
        public string NotParticipateinCS { get; set; }
        public string DentalCondition { get; set; }
        public string ExtraOral { get; set; }
        public string IntraOral { get; set; }
        public string ToothCavity { get; set; }
        public string Plaque { get; set; }
        public string Guminfl { get; set; }
        public string Stains { get; set; }
        public string Tarter { get; set; }
        public string BadBreath { get; set; }
        public string GumBleeding { get; set; }
        public string SoftTissue { get; set; }
        public string RespExam { get; set; }
        public string Cardiosys { get; set; }
        public string Abdomen { get; set; }
        public string Nervoussys { get; set; }
        public string ImpFindings { get; set; }
        public string Remarks { get; set; }
        public string PastDisease { get; set; }
        public string PastSurgery { get; set; }
        public string PastAllergie { get; set; }
        public string PastMedication { get; set; }
        public string PastIllness { get; set; }
        public string PastDiseaseRec { get; set; }
        public string PastSurgeryRec { get; set; }
        public string PastAllergieRec { get; set; }
        public string PastMedicationRec { get; set; }
        public string PastIllnessRec { get; set; }
        public string FamilyDoctorName { get; set; }
        public string FamilyDoctorMobile { get; set; }
        public string NeighbourPhone { get; set; }
        public string RelativePhone { get; set; }
    }
}
